version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "/wait_for_db.sh &&
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn smart.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./smart:/code
      - static_volume:/code/staticfiles
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=database
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=smart
      - DJANGO_DB_USER=smart
      - DJANGO_DB_PASSWORD=smart
    expose:
      - "8000"
    depends_on:
      - database

  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: smart
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: smart

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume: